use dashboard::Dashboard;
use media_player::MediaPlayerWindow;
use calendar::Calendar;
use audio_mixer::AudioMixerPopup;
use cliphist;
use notification_popups::NotificationPopups;
use overview::Overview;
use session_control::sessioncontrols;
use power_profile::pwrprofiles;
use launcher::Launcher;

pub use dashboard::Dashboard;
pub use media_player::MediaPlayerWindow;
pub use calendar::Calendar;
pub use audio_mixer::AudioMixerPopup;
pub use cliphist;
pub use notification_popups::NotificationPopups;
pub use overview::Overview;
pub use session_control::sessioncontrols;
pub use power_profile::pwrprofiles;
pub use launcher::Launcher;